namespace AlbionStaticDataLib.Input.Items.Models

{
    public enum FurnitureitemUicraftsoundstart { PlayUiActionCraftFlourStart, PlayUiActionCraftFoodFirmStart, PlayUiActionCraftFoodFryStart, PlayUiActionCraftFoodLiquidStart, PlayUiActionCraftMeatStart, PlayUiActionCraftRefineFiberStart, PlayUiActionCraftRefineHideStart, PlayUiActionCraftRefineOreStart, PlayUiActionCraftRefineStoneStart, PlayUiActionCraftRefineWoodStart };
}
