namespace AlbionStaticDataLib.Input.Items.Models

{
    public enum FurnitureitemUicraftsoundfinish { PlayUiActionCraftFlourFinish, PlayUiActionCraftFoodFinish, PlayUiActionCraftMeatFinish, PlayUiActionCraftRefineFiberFinish, PlayUiActionCraftRefineHideFinish, PlayUiActionCraftRefineOreFinish, PlayUiActionCraftRefineStoneFinish, PlayUiActionCraftRefineWoodFinish };
}
